### ISSUE TITLE
Issue - Your connection is not private

### ISSUE THREAD

**Issue by cavo789** [tshenolo/docker-Secure-Apache#1]
Hi !

Thanks for the tutorial on Medium and this repo.

I've followed exactly what you've explained on, first Medium then by just downloading this repo but everytime I got the "Your connection is not private" issue:

![2024-08-15_18h44_49](https://github.com/user-attachments/assets/c138d3b2-7df9-4854-a082-2faa2d79e893)

Tried on Firefox, Edge and Chrome.
Windows 11 / WSL2

**Comment by cavo789** [comment]
Found. We need to create an exception for self-signed certificate. To do this, we need to visit [chrome://flags/#temporary-unexpire-flags-m118](chrome://flags/#temporary-unexpire-flags-m118), search for *localhost* and enable the option.

**Comment by tshenolo** [comment]
@cavo789 Thanks for reaching out.
I am glad you found the tutorial useful.
